language: go

sudo: false

go:
  - 1.6.2
  - tip

before_install:
  - go get -v github.com/golang/lint/golint

install: go get -v -d -t ./...

script:
  - go test -v -cover -coverprofile=coverage.txt -covermode=atomic
  - gofmt -d .
  - go tool vet .
  - golint .

after_success:
  - bash <(curl -s https://codecov.io/bash)
